runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
env_variables:
    GCLOUD_PROJECT: serverlessmicroservice
    SPANNER_INSTANCE: test-instance
    SPANNER_DB_NAME: example-db
libraries:
- name: pycrypto
  version: "2.6"
